FILES	=	kernel \
			terminal/terminal_screen \
			terminal/terminal_color \
			terminal/terminal_render \
			terminal/terminal_cursor \
			terminal/terminal_input \
			terminal/terminal_output \
			keyboard/keyboard \
			keyboard/keyboard_maps \
			printk \
			bash/bash \
			bash/fault \
			bash/dump \
			bash/shutdown \
			bash/reboot \
			bash/halt \
			bash/flags \
			bash/echo \
			bash/help \
			bash/paging \
			bash/test_malloc \
			bash/test_free \
			bash/layout \
			bash/panic \
			helpers \
			memory/pfa \
			gdt \
			memory/paging \
			panic \
			memory/vmm \
			memory/kmalloc \
			idt_init \
			handler \
			syscall
